db_name : test_db
db_port: 3306
db_ip: 47.98.132.116:${db_port}

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${db_ip}/${db_name}?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: T_dl123456



logging:
    level:
      org.alvin.springjdbc.system: debug