server:
  port: 8092
spring:
  profiles:
    active: dev
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.98.132.116:3306/test_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: T_dl123456